version: "3.8"

services:
  home-api:
    image: 192.168.1.136/home-api:latest # Substitua pelo caminho correto da imagem no seu registro Docker
    container_name: home-api
    environment:
      SPRING_PROFILES_ACTIVE: prod # Define o profile ativo do Spring (caso necessário)
      DB_URL: ${DB_URL} # Obtém o URL do banco de dados da variável de ambiente do host
      DB_USERNAME: ${DB_USERNAME} # Obtém o usuário do banco de dados da variável de ambiente do host
      DB_PASSWORD: ${DB_PASSWORD} #
      SERVER_PORT: 8080
    ports:
      - "8080:8080" # Mapeando a porta 8080 para o host
    restart: unless-stopped # Reinicia automaticamente o container em caso de falha